# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pbjES <- function(mu, M, chsq, df, nboot) {
    .Call(`_pbj_pbjES`, mu, M, chsq, df, nboot)
}

pbjESboundary <- function(M, nboot) {
    .Call(`_pbj_pbjESboundary`, M, nboot)
}

