# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcBootStats <- function(images, X, Xred, coefficients, peind) {
    .Call(`_pbj_calcBootStats`, images, X, Xred, coefficients, peind)
}

pbjES <- function(mu, M, k, df, nboot) {
    .Call(`_pbj_pbjES`, mu, M, k, df, nboot)
}

pbjESzerodf <- function(mu, M, k, nboot) {
    .Call(`_pbj_pbjESzerodf`, mu, M, k, nboot)
}

pbjESboundary <- function(M, nboot) {
    .Call(`_pbj_pbjESboundary`, M, nboot)
}

